<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt-BR" xml:lang="pt-BR"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Prof.&nbsp;Dr.&nbsp;Lindomar Pegorini Daniel — UNEMAT, Campus de Sinop">

<title>Casos reais de financiamento – Financiamento da Inovação · UNEMAT</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-e81378a2c5a241eb1d7068b9d6053de7.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="site_libs/quarto-contrib/live-runtime/live-runtime.js" type="module"></script>
<link href="site_libs/quarto-contrib/live-runtime/live-runtime.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Nenhum resultado",
    "search-matching-documents-text": "documentos correspondentes",
    "search-copy-link-title": "Copiar link para a busca",
    "search-hide-matches-text": "Esconder correspondências adicionais",
    "search-more-match-text": "mais correspondência neste documento",
    "search-more-matches-text": "mais correspondências neste documento",
    "search-clear-button-title": "Limpar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Procurar"
  }
}</script>
<style>

      .quarto-title-block .quarto-title-banner h1,
      .quarto-title-block .quarto-title-banner h2,
      .quarto-title-block .quarto-title-banner h3,
      .quarto-title-block .quarto-title-banner h4,
      .quarto-title-block .quarto-title-banner h5,
      .quarto-title-block .quarto-title-banner h6
      {
        color: white;
      }

      .quarto-title-block .quarto-title-banner {
        color: white;
background: #1E2761;
      }
</style>
<script type="module" src="site_libs/quarto-ojs/quarto-ojs-runtime.js"></script>
<link href="site_libs/quarto-ojs/quarto-ojs.css" rel="stylesheet">


</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Financiamento da Inovação · UNEMAT</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Procurar"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Alternar de navegação" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Início</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./roteiro.html"> 
<span class="menu-text">Roteiro</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-aulas" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Aulas</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-aulas">    
        <li class="dropdown-header">— Sábado 1 · 12/09 —</li>
        <li>
    <a class="dropdown-item" href="./s1-01-politicas-publicas.html">
 <span class="dropdown-text">Políticas públicas: conceito e ciclo</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./s1-02-sistema-cti.html">
 <span class="dropdown-text">O sistema brasileiro de CT&amp;I</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./s1-03-avaliacao.html">
 <span class="dropdown-text">Avaliação: o que o financiador cobra</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./s1-04-contrafactual.html">
 <span class="dropdown-text">O contrafactual</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">— Sábado 2 · 26/09 —</li>
        <li>
    <a class="dropdown-item" href="./s2-01-nao-reembolsavel.html">
 <span class="dropdown-text">Fomento não reembolsável</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./s2-02-embrapii.html">
 <span class="dropdown-text">EMBRAPII: o instrumento sem edital</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./s2-03-incentivos-fiscais.html">
 <span class="dropdown-text">Incentivos fiscais</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./s2-04-credito-e-capital-privado.html">
 <span class="dropdown-text">Crédito e capital privado</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-catálogo" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Catálogo</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-catálogo">    
        <li>
    <a class="dropdown-item" href="./cat-escada.html">
 <span class="dropdown-text">A escada do financiamento</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./casos-reais.html">
 <span class="dropdown-text">Casos reais de financiamento</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./cat-nao-reembolsavel.html">
 <span class="dropdown-text">Não reembolsável</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./cat-fiscais.html">
 <span class="dropdown-text">Incentivos fiscais</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./cat-credito.html">
 <span class="dropdown-text">Crédito</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./cat-privado.html">
 <span class="dropdown-text">Capital privado</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-laboratórios" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Laboratórios</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-laboratórios">    
        <li>
    <a class="dropdown-item" href="./lab01-explorando-dados.html">
 <span class="dropdown-text">Laboratório 1 — Explorando os dados de um programa</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./lab02-did.html">
 <span class="dropdown-text">Laboratório 2 — Diferenças-em-diferenças</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./lab03-vpl-tir.html">
 <span class="dropdown-text">Laboratório 3 — Vale a pena? VPL, TIR e payback</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./lab04-custo-das-fontes.html">
 <span class="dropdown-text">Laboratório 4 — O custo real de cada fonte</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-avaliação" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Avaliação</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-avaliação">    
        <li>
    <a class="dropdown-item" href="./casos.html">
 <span class="dropdown-text">Os dez casos</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./atividade-mapa.html">
 <span class="dropdown-text">Mapa de instrumentos</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./caso-lei-do-bem.html">
 <span class="dropdown-text">O caso da Lei do Bem</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./atividade-elegibilidade.html">
 <span class="dropdown-text">Esta empresa pode usar a Lei do Bem?</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./trabalho-final.html">
 <span class="dropdown-text">Trabalho final</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-slides" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Slides</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-slides">    
        <li>
    <a class="dropdown-item" href="./slides-s1.html">
 <span class="dropdown-text">Por que existe esse dinheiro</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./slides-s2.html">
 <span class="dropdown-text">De onde vem o dinheiro</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="./leituras.html"> 
<span class="menu-text">Leituras</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Casos reais de financiamento</h1>
            <p class="subtitle lead">Oito histórias com número, fonte e data — uma para cada porta do catálogo</p>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Autor</div>
      <div class="quarto-title-meta-contents">
               <p>Prof.&nbsp;Dr.&nbsp;Lindomar Pegorini Daniel — UNEMAT, Campus de Sinop </p>
            </div>
    </div>
      
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Nesta página</h2>
   
  <ul>
  <li><a href="#finep-regional" id="toc-finep-regional" class="nav-link active" data-scroll-target="#finep-regional"><span class="header-section-number">1</span> Finep Subvenção Econômica Regional 2026 — a chance de aprovação com número real</a></li>
  <li><a href="#centelha" id="toc-centelha" class="nav-link" data-scroll-target="#centelha"><span class="header-section-number">2</span> Centelha 3 — Mato Grosso: o funil de um programa estadual</a></li>
  <li><a href="#startup-mt" id="toc-startup-mt" class="nav-link" data-scroll-target="#startup-mt"><span class="header-section-number">3</span> Startup Mato Grosso — dez vagas de R$ 150 mil</a></li>
  <li><a href="#inova-mt" id="toc-inova-mt" class="nav-link" data-scroll-target="#inova-mt"><span class="header-section-number">4</span> Inova Mato Grosso — quando o financiamento é uma pessoa</a></li>
  <li><a href="#embrapii" id="toc-embrapii" class="nav-link" data-scroll-target="#embrapii"><span class="header-section-number">5</span> IOTIC Consultoria e o Polo EMBRAPII do IFTM — os três terços na prática</a></li>
  <li><a href="#desenvolve-mt" id="toc-desenvolve-mt" class="nav-link" data-scroll-target="#desenvolve-mt"><span class="header-section-number">6</span> Desenvolve MT e a hidroponia de Juara — dívida com carência casada com a colheita</a></li>
  <li><a href="#produzindo-certo" id="toc-produzindo-certo" class="nav-link" data-scroll-target="#produzindo-certo"><span class="header-section-number">7</span> Produzindo Certo — o que o investidor compra</a></li>
  <li><a href="#lei-do-bem" id="toc-lei-do-bem" class="nav-link" data-scroll-target="#lei-do-bem"><span class="header-section-number">8</span> Lei do Bem no Centro-Oeste — quem usa, sem os nomes</a></li>
  <li><a href="#antes-de-sair" id="toc-antes-de-sair" class="nav-link" data-scroll-target="#antes-de-sair"><span class="header-section-number">9</span> Antes de sair</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<div class="logo-topo">
<p><img src="logo-unemat.png" class="img-fluid" width="110"></p>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>O que esta página resolve
</div>
</div>
<div class="callout-body-container callout-body">
<p>Os <a href="./casos.html">dez casos</a> da disciplina são fictícios de propósito: servem para praticar sem constranger ninguém. Esta página faz o contrário — junta situações <strong>reais</strong>, com nomes, valores e datas públicas, uma para cada natureza do dinheiro. Cada caso termina com o que ele ensina e com o lugar do site em que a lição é usada.</p>
<p>Todos os números vêm de fontes abertas, citadas ao fim de cada caso, e foram levantados em <strong>23/09/2026</strong>. Valores, prazos e condições envelhecem; confira na fonte antes de usar num plano.</p>
</div>
</div>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Caso</th>
<th>Natureza</th>
<th>O número que fica</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><a href="#finep-regional">Finep Subvenção Regional 2026</a></td>
<td><span class="nat nat-nr">Não reembolsável</span></td>
<td>R$ 2,18 bilhões pedidos para R$ 300 milhões</td>
</tr>
<tr class="even">
<td><a href="#centelha">Centelha 3 — Mato Grosso</a></td>
<td><span class="nat nat-nr">Não reembolsável</span></td>
<td>813 ideias, 47 financiadas</td>
</tr>
<tr class="odd">
<td><a href="#startup-mt">Startup Mato Grosso</a></td>
<td><span class="nat nat-nr">Não reembolsável</span></td>
<td>10 vagas de R$ 150 mil</td>
</tr>
<tr class="even">
<td><a href="#inova-mt">Inova Mato Grosso</a></td>
<td><span class="nat nat-nr">Não reembolsável</span></td>
<td>um mestre por empresa, doze meses</td>
</tr>
<tr class="odd">
<td><a href="#embrapii">IOTIC + Polo EMBRAPII do IFTM</a></td>
<td><span class="nat nat-nr">Não reembolsável</span></td>
<td>R$ 907 mil: 50% · 20% · 30%</td>
</tr>
<tr class="even">
<td><a href="#desenvolve-mt">Desenvolve MT e a hidroponia de Juara</a></td>
<td><span class="nat nat-reemb">Reembolsável</span></td>
<td>70% financiado, carência até a colheita</td>
</tr>
<tr class="odd">
<td><a href="#produzindo-certo">Produzindo Certo</a></td>
<td><span class="nat nat-eq">Equity</span></td>
<td>Série A de R$ 20,7 milhões</td>
</tr>
<tr class="even">
<td><a href="#lei-do-bem">Lei do Bem no Centro-Oeste</a></td>
<td><span class="nat nat-fis">Fiscal</span></td>
<td>129 empresas, R$ 868 milhões em P&amp;D</td>
</tr>
</tbody>
</table>
<section id="finep-regional" class="level2 ficha nr" data-number="1">
<h2 class="ficha nr anchored" data-number="1" data-anchor-id="finep-regional"><span class="header-section-number">1</span> Finep Subvenção Econômica Regional 2026 — a chance de aprovação com número real</h2>
<p>Em fevereiro de 2026 a Finep abriu, com a SUDAM, a SUDENE, a SUDECO e o Sebrae, um edital de subvenção só para empresas do Norte, do Nordeste e do Centro-Oeste. É a chamada mais próxima do perfil desta turma que existiu no ano — e o que ela ensina está no que aconteceu depois do prazo.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<tbody>
<tr class="odd">
<td><strong>Recursos</strong></td>
<td>R$ 300 milhões, não reembolsáveis: R$ 50 milhões para o Norte, R$ 150 milhões para o Nordeste e <strong>R$ 100 milhões para o Centro-Oeste</strong></td>
</tr>
<tr class="even">
<td><strong>Por proposta</strong></td>
<td>De R$ 2 milhões a R$ 5 milhões</td>
</tr>
<tr class="odd">
<td><strong>Quem pode</strong></td>
<td>Empresa com sede nas três regiões e receita bruta anual até R$ 90 milhões; cerca de 30% dos recursos reservados a micro e pequenas (receita até R$ 4,8 milhões)</td>
</tr>
<tr class="even">
<td><strong>Contrapartida</strong></td>
<td>5% do valor concedido</td>
</tr>
<tr class="odd">
<td><strong>Temas</strong></td>
<td>As missões da Nova Indústria Brasil: transição energética, cadeias industriais, saúde, tecnologias digitais, defesa, transformação mineral, economia circular, cidades sustentáveis, mobilidade, semicondutores e agricultura familiar</td>
</tr>
<tr class="even">
<td><strong>Prazo</strong></td>
<td>07/04/2026</td>
</tr>
<tr class="odd">
<td><strong>Demanda</strong></td>
<td><strong>568 propostas, pedindo R$ 2,18 bilhões</strong> — 7,3 vezes o orçamento. 432 propostas (76%) de empresas com receita até R$ 4,8 milhões; 483 (85%) com uma ICT parceira, somando R$ 239 milhões destinados às ICTs</td>
</tr>
</tbody>
</table>
<p><strong>A conta.</strong> R$ 300 milhões para R$ 2,18 bilhões pedidos é 13,8% do dinheiro. Se todas as propostas pedissem o mesmo valor, a chance de uma delas ser contemplada seria de cerca de <strong>uma em sete</strong> — antes de qualquer juízo de mérito. É exatamente o número que o <a href="./lab04-custo-das-fontes.html">Laboratório 4</a> pede para calcular o ganho esperado de concorrer, e é por isso que o custo de escrever a proposta entra na conta.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>O que este caso ensina
</div>
</div>
<div class="callout-body-container callout-body">
<p>Três coisas. Primeiro, que subvenção federal de porte existe para o Centro-Oeste, e a SUDECO está na mesa. Segundo, que “quanto pede” e “quanto há” andam muito longe um do outro — 7 para 1 num edital regional, com apoio de aceleração do Sebrae na conta. Terceiro, que 85% das propostas chegaram com uma ICT parceira: para um edital assim, a parceria com universidade ou instituto não é enfeite, é requisito de competitividade. Usado na <a href="./s2-01-nao-reembolsavel.html">Aula 5</a> e no Laboratório 4.</p>
</div>
</div>
<p>Fontes: <a href="https://www.campograndenews.com.br/economia/ms-disputa-r-100-milhoes-de-subvencao-para-inovacao-de-empresas-no-centro-oeste">Campo Grande News, 18/02/2026</a> · <a href="https://agenciasebrae.com.br/inovacao-e-tecnologia/ultimos-dias-edital-de-r-300-mi-da-finep-seleciona-startups-do-norte-nordeste-e-centro-oeste/">Agência Sebrae de Notícias, 03/04/2026</a> · <a href="https://www.finep.gov.br/noticias/todas-noticias/7152-edital-de-subvencao-economica-regional-568-propostas-recebidas-e-demanda-de-r-2-18-bi">Finep, notícia sobre a demanda, maio de 2026</a> · <a href="https://rochamarques.com.br/edital-de-subvencao-economica-regional-supera-expectativas-e-registra-demanda-de-r-218-bilhoes/">Rocha Marques, 01/05/2026</a></p>
</section>
<section id="centelha" class="level2 ficha nr" data-number="2">
<h2 class="ficha nr anchored" data-number="2" data-anchor-id="centelha"><span class="header-section-number">2</span> Centelha 3 — Mato Grosso: o funil de um programa estadual</h2>
<p>O Centelha financia ideias de quem ainda não tem empresa. A terceira edição mato-grossense, lançada em 20/10/2025 pela Seciteci e pela Fapemat com recursos da Finep, mostra o formato do funil melhor do que qualquer definição.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Etapa</th>
<th>Número</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Ideias inscritas</td>
<td><strong>813</strong>, de 1.832 empreendedores em 45 municípios — 116,8% mais do que na edição anterior</td>
</tr>
<tr class="even">
<td>Aprovadas na fase 1</td>
<td>200</td>
</tr>
<tr class="odd">
<td>Financiadas</td>
<td><strong>47</strong> projetos (resultado em 02/07/2026)</td>
</tr>
<tr class="even">
<td>Por projeto</td>
<td>Até <strong>R$ 86 mil</strong> de subvenção, mais bolsa de até R$ 50 mil do CNPq</td>
</tr>
<tr class="odd">
<td>Total</td>
<td>R$ 6,1 milhões</td>
</tr>
<tr class="even">
<td>Setores mais frequentes entre os aprovados</td>
<td>Farmoquímico e farmacêutico (40%); meio ambiente e bioeconomia (9%); eletroeletrônica, borracha e plástico, segurança e defesa (6% cada)</td>
</tr>
<tr class="odd">
<td>Edições anteriores</td>
<td>Mais de 873 ideias e 75 startups criadas</td>
</tr>
</tbody>
</table>
<p><strong>A conta.</strong> 47 em 813 é <strong>5,8%</strong>. A fase 1 corta três em cada quatro; a fase 2, três em cada quatro de novo. Quem entende o funil não se inscreve com a ideia crua: usa a capacitação entre as fases, que faz parte do programa, para chegar à segunda etapa com modelo de negócio e pitch prontos.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>O que este caso ensina
</div>
</div>
<div class="callout-body-container callout-body">
<p>O tíquete é pequeno e a disputa é grande, mas é a única porta do sistema que aceita pessoa física — o CNPJ vem depois da aprovação. Para quem tem ideia e não tem empresa, o Centelha é o começo da <a href="./cat-escada.html">escada</a>, e o ciclo é de dois a três anos: a quarta edição é a que vale acompanhar. Usado na <a href="./s2-01-nao-reembolsavel.html">Aula 5</a> e na ficha do <a href="./cat-nao-reembolsavel.html#centelha">catálogo</a>.</p>
</div>
</div>
<p>Fontes: <a href="https://programacentelha.com.br/centelha-mato-grosso-confira-os-principais-resultados-da-terceira-edicao-do-programa-no-estado/">Programa Centelha, resultados da 3ª edição em MT, 02/07/2026</a> · <a href="https://www.folhamax.com/cidades/lista-traz-aprovados-para-a-3-edicao-do-programa-centelha/537433">FolhaMax, 18/02/2026</a></p>
</section>
<section id="startup-mt" class="level2 ficha nr" data-number="3">
<h2 class="ficha nr anchored" data-number="3" data-anchor-id="startup-mt"><span class="header-section-number">3</span> Startup Mato Grosso — dez vagas de R$ 150 mil</h2>
<p>É o edital dissecado item por item na <a href="./s2-01-nao-reembolsavel.html">Aula 5</a>. Aqui ficam só os números de cabeçalho, para comparação com os outros casos.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<tbody>
<tr class="odd">
<td><strong>Chamada</strong></td>
<td>Fapemat, Chamada Pública nº 04/2026 — Startup Mato Grosso, lançada em 03/07/2026</td>
</tr>
<tr class="even">
<td><strong>Recursos</strong></td>
<td>R$ 1,5 milhão, não reembolsáveis</td>
</tr>
<tr class="odd">
<td><strong>Por empresa</strong></td>
<td>Até R$ 150 mil; até <strong>10 empresas</strong></td>
</tr>
<tr class="even">
<td><strong>Quem pode</strong></td>
<td>Empresa com sede ou filial em Mato Grosso, entre 2 e 10 anos de existência, receita bruta até R$ 16 milhões, atividade operacional comprovada em 2025; aceita o regime Inova Simples</td>
</tr>
<tr class="odd">
<td><strong>Calendário</strong></td>
<td>Inscrições até 31/07/2026; avaliação em agosto e início de setembro; <strong>resultado em 16/09/2026</strong>; contratação a partir de 17/09</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>O que este caso ensina
</div>
</div>
<div class="callout-body-container callout-body">
<p>Compare com o Centelha: dez vezes o valor por projeto, mas para empresa já operando há pelo menos dois anos. Cada degrau da escada tem o seu edital, e o erro mais comum é concorrer no degrau errado. A lista das dez selecionadas saiu em 16/09; confira no site da Fapemat — e note quantas das dez são de fora de Cuiabá.</p>
</div>
</div>
<p>Fontes: <a href="https://cenariomt.com.br/mato-grosso/edital-startup-mato-grosso-vai-injetar-r-15-milhao-em-empresas-inovadoras/">CenárioMT, 03/07/2026</a> · <a href="https://www.fapemat.mt.gov.br/w/fapemat-lan%C3%A7a-edital-de-r-1-5-milh%C3%A3o-para-impulsionar-inova%C3%A7%C3%A3o-e-fortalecer-empresas-no-estado">Fapemat, 03/07/2026</a></p>
</section>
<section id="inova-mt" class="level2 ficha nr" data-number="4">
<h2 class="ficha nr anchored" data-number="4" data-anchor-id="inova-mt"><span class="header-section-number">4</span> Inova Mato Grosso — quando o financiamento é uma pessoa</h2>
<p>Nem todo apoio não reembolsável é um cheque. Na quarta edição do prêmio Inova Mato Grosso (abril de 2025), Fapemat, Seciteci e Parque Tecnológico destinaram <strong>R$ 540 mil</strong> a nove empresas — e o apoio veio na forma de um <strong>bolsista com mestrado trabalhando dentro da empresa por doze meses</strong>, além de missões de benchmarking e entrada no ecossistema do Parque.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Categoria</th>
<th>Empresas premiadas</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Microempresas</td>
<td>Namaskar Comunicação e Projetos (Rondonópolis) · Thotia Corp (Alto Araguaia) · Agrosolo (Nova Mutum) · Escopo Soluções (Alta Floresta) · Quero + Alimentos (Barra do Garças)</td>
</tr>
<tr class="even">
<td>Pequenas empresas</td>
<td>Avante Assessoria Contábil e Empresarial (Cuiabá) · Ganmaq (Primavera do Leste) · <strong>Spectrax (Sinop)</strong> · Piolê (Cuiabá)</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>O que este caso ensina
</div>
</div>
<div class="callout-body-container callout-body">
<p>Lembre da situação do <a href="./atividade-mapa.html">Mapa de instrumentos</a> em que o gasto era em gente, não em equipamento: este é o instrumento que financia gente. Sessenta mil reais por empresa não compram máquina, mas pagam um ano de um profissional qualificado dedicado a um problema — e nove das dez cidades da lista estão fora da capital. O parente federal é o <a href="./cat-nao-reembolsavel.html">RHAE do CNPq</a>, com a mesma lógica.</p>
</div>
</div>
<p>Fonte: <a href="https://www.folhamax.com/economia/empresas-de-todas-as-regioes-do-estado-sao-premiadas-no-inova-mt/486058">FolhaMax, 11/04/2025</a></p>
</section>
<section id="embrapii" class="level2 ficha nr" data-number="5">
<h2 class="ficha nr anchored" data-number="5" data-anchor-id="embrapii"><span class="header-section-number">5</span> IOTIC Consultoria e o Polo EMBRAPII do IFTM — os três terços na prática</h2>
<p>O primeiro projeto contratado pelo Polo de Inovação do Instituto Federal do Triângulo Mineiro, em Uberaba (MG), é um equipamento de <strong>espectroscopia no infravermelho próximo (NIR)</strong> para analisar parâmetros do milho de forma instantânea, sem destruir a amostra e sem reagentes químicos. A empresa é a IOTIC Consultoria; a divisão do custo é a que interessa.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>Valor</th>
<th>Parcela</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Total do projeto</strong></td>
<td>R$ 907.392,86</td>
<td>100%</td>
</tr>
<tr class="even">
<td>EMBRAPII</td>
<td>R$ 453.696</td>
<td><strong>50%</strong></td>
</tr>
<tr class="odd">
<td>IOTIC Consultoria (empresa)</td>
<td>R$ 182.114</td>
<td><strong>20,07%</strong></td>
</tr>
<tr class="even">
<td>Polo IFTM (Unidade)</td>
<td>R$ 271.583</td>
<td><strong>29,93%</strong></td>
</tr>
</tbody>
</table>
<p>A EMBRAPII entrou com metade — a regra dos 50% para empresa com receita até R$ 90 milhões — e a Unidade cobriu quase 30% com sua própria estrutura, o que deixou à empresa cerca de um quinto do projeto em dinheiro. Não houve edital: a empresa procurou a Unidade e contratou.</p>
<p><strong>E em Mato Grosso.</strong> O IFMT foi credenciado em abril de 2026 como a primeira Unidade EMBRAPII do estado, em tecnologias digitais para a agroindústria. Na média da rede, segundo a própria EMBRAPII, a divisão é 34% EMBRAPII, 49,9% empresas e 15% Unidades; desde a criação foram 3.982 projetos com 2.709 empresas e R$ 7,8 bilhões em P&amp;D.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>O que este caso ensina
</div>
</div>
<div class="callout-body-container callout-body">
<p>A conta da <a href="./s2-02-embrapii.html">Aula 6</a> com um projeto de verdade: para uma empresa pequena, o aporte em dinheiro pode ficar perto de 20% se a Unidade trouxer estrutura e equipe. O detalhe que decide é a contrapartida <strong>em dinheiro</strong> — horas de equipe da empresa não contam. E o projeto tem cara de agro mato-grossense: milho, análise de grão, sem laboratório. Usado na Aula 6 e na ficha da <a href="./cat-nao-reembolsavel.html">EMBRAPII</a>.</p>
</div>
</div>
<p>Fontes: <a href="https://iftm.edu.br/embrapii/projetos/projeto-01/">Polo de Inovação do IFTM, projeto 01</a> · <a href="https://mtplay.com.br/agronegocio/primeira-unidade-embrapii-em-mt-sera-voltada-a-tecnologias-digitais-para-agroindustria/">MT Play, 20/04/2026</a></p>
</section>
<section id="desenvolve-mt" class="level2 ficha reemb" data-number="6">
<h2 class="ficha reemb anchored" data-number="6" data-anchor-id="desenvolve-mt"><span class="header-section-number">6</span> Desenvolve MT e a hidroponia de Juara — dívida com carência casada com a colheita</h2>
<p>Dois lados do mesmo balcão. Em setembro de 2025 a Desenvolve MT anunciou <strong>R$ 43 milhões</strong> da linha Inovacred, com funding da Finep, para empresas e cooperativas de Mato Grosso: até R$ 5 milhões por operação, até 120 meses de prazo, até 24 meses de carência, juros de TR + 6,068% ao ano para micro e pequenas e TR + 6,606% para médias e grandes (as condições vigentes estão na ficha do <a href="./cat-credito.html">catálogo</a>, que muda com frequência).</p>
<p>Três meses antes, em junho de 2025, a mesma agência divulgou um contrato pequeno e didático: a <strong>Hortifruti Vovó Vaci</strong>, de Juara, no noroeste do estado, financiou pela linha Desenvolve Empresarial a implantação de um sistema hidropônico — estufas, estruturas, irrigação e dois poços artesianos, mais de 3.000 m² de área útil.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<tbody>
<tr class="odd">
<td><strong>O que foi financiado</strong></td>
<td>Estufas, estruturas, sistema de irrigação, dois poços artesianos</td>
</tr>
<tr class="even">
<td><strong>Quanto</strong></td>
<td>Cerca de <strong>70% do custo total</strong> do projeto (o valor não foi divulgado)</td>
</tr>
<tr class="odd">
<td><strong>Prazo</strong></td>
<td>Até 120 meses, com <strong>12 meses de carência</strong></td>
</tr>
<tr class="even">
<td><strong>Produção</strong></td>
<td>Alface, rúcula, cebolinha, coentro, salsa, tomate-cereja e mais de 400 variedades de ervas; venda direta e entrega a mercados e residências</td>
</tr>
<tr class="odd">
<td><strong>Calendário</strong></td>
<td>Contrato divulgado em 28/06/2025; primeiras colheitas previstas para o fim de agosto de 2025</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>O que este caso ensina
</div>
</div>
<div class="callout-body-container callout-body">
<p>Crédito serve para o que a subvenção quase nunca paga: obra, estufa, poço, equipamento — e serve porque tem carência. Os doze meses sem parcela cobrem o intervalo entre o investimento e a primeira colheita; é a carência que faz a dívida caber no fluxo de caixa, e é o que a <a href="./s2-04-credito-e-capital-privado.html">Aula 8</a> e o <a href="./lab04-custo-das-fontes.html">Laboratório 4</a> pedem que se calcule. Repare também no que a fonte não diz: o valor. Toda notícia de crédito esconde o número que mais importa.</p>
</div>
</div>
<p>Fontes: <a href="https://desenvolve.mt.gov.br/noticias/empresas-de-mato-grosso-terao-r-43-milhoes-disponiveis-para-inovacao-pela-desenvolve-mt">Desenvolve MT, 06/09/2025 (R$ 43 milhões)</a> · <a href="https://desenvolve.mt.gov.br/noticias/credito-da-desenvolve-mt-viabiliza-inovacao-tecnologica-com-implantacao-de-hidroponia-em-juara-1">Desenvolve MT, 28/06/2025 (Juara)</a></p>
</section>
<section id="produzindo-certo" class="level2 ficha eq" data-number="7">
<h2 class="ficha eq anchored" data-number="7" data-anchor-id="produzindo-certo"><span class="header-section-number">7</span> Produzindo Certo — o que o investidor compra</h2>
<p>Uma agtech do Centro-Oeste com uma rodada de porte. A Produzindo Certo, de Rio Verde (GO), verifica e gerencia a sustentabilidade de cadeias agrícolas com uma plataforma que combina visitas de campo e monitoramento remoto. Em outubro de 2025 fechou a primeira rodada institucional.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<tbody>
<tr class="odd">
<td><strong>Rodada</strong></td>
<td>Série A de <strong>R$ 20,7 milhões</strong> — a meta inicial era R$ 10 milhões</td>
</tr>
<tr class="even">
<td><strong>Quem investiu</strong></td>
<td>Arar Capital e SP Ventures, na liderança; The Yield Lab Latam, Agroven e <strong>SLC Ventures</strong>, o braço de corporate venture da SLC Agrícola</td>
</tr>
<tr class="odd">
<td><strong>O que o dinheiro compra</strong></td>
<td>Equipe de tecnologia, comercial e marketing; produto e operação em agricultura regenerativa e pecuária sustentável</td>
</tr>
<tr class="even">
<td><strong>A tração que sustentou a rodada</strong></td>
<td>Mais de 10.700 propriedades cadastradas, 8,6 milhões de hectares monitorados, mais de 3,5 milhões de hectares de vegetação nativa conservada, 40 clientes corporativos — entre eles Unilever, Nestlé, ADM, Bunge e Brasilseg</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>O que este caso ensina
</div>
</div>
<div class="callout-body-container callout-body">
<p>O investidor não comprou uma ideia: comprou 10.700 propriedades, 8,6 milhões de hectares e 40 contratos com grandes compradores. Rodada assim vem depois da tração, não antes — o que explica por que a maioria dos bons projetos de inovação desta turma <strong>não</strong> é caso de venture capital, e não é defeito do projeto. E note a SLC Ventures: o próprio agro investindo em agtech, o corporate venture da <a href="./s2-04-credito-e-capital-privado.html">Aula 8</a> e da ficha de <a href="./cat-privado.html">capital privado</a>.</p>
</div>
</div>
<p>Fonte: <a href="https://agfeed.com.br/agtech/produzindo-certo-colhe-r-207-milhoes-em-rodada-com-grandes-nomes-do-investimento-agtech/">AgFeed, 24/10/2025</a></p>
</section>
<section id="lei-do-bem" class="level2 ficha fis" data-number="8">
<h2 class="ficha fis anchored" data-number="8" data-anchor-id="lei-do-bem"><span class="header-section-number">8</span> Lei do Bem no Centro-Oeste — quem usa, sem os nomes</h2>
<p>Os nomes das empresas que usam a Lei do Bem não são públicos: o MCTI divulga os dados abertos <strong>sem identificação</strong>, uma linha por empresa, com região, CNAE, número de projetos e dispêndio declarado em P&amp;D (série 2015–2021). Mesmo assim, a base diz muito sobre quem consegue usar o incentivo aqui perto.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Centro-Oeste, ano-base</th>
<th>Empresas</th>
<th>Projetos</th>
<th>Dispêndio declarado</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2015</td>
<td>35</td>
<td>130</td>
<td>R$ 138 milhões</td>
</tr>
<tr class="even">
<td>2017</td>
<td>67</td>
<td>308</td>
<td>R$ 337 milhões</td>
</tr>
<tr class="odd">
<td>2019</td>
<td>93</td>
<td>275</td>
<td>R$ 446 milhões</td>
</tr>
<tr class="even">
<td>2021</td>
<td><strong>129</strong></td>
<td><strong>384</strong></td>
<td><strong>R$ 868 milhões</strong></td>
</tr>
</tbody>
</table>
<p>Em 2021, no Centro-Oeste: a <strong>indústria</strong> (41 empresas) declarou R$ 364 milhões; os <strong>bancos</strong> (11 empresas), R$ 146 milhões; as empresas de <strong>tecnologia da informação</strong> (23), R$ 93 milhões. A <strong>agropecuária</strong> apareceu com sete empresas — quatro produtoras de soja (uma delas com R$ 56 milhões em dois projetos), duas de pecuária de corte e uma de pós-colheita; um <strong>frigorífico</strong> de bovinos declarou R$ 22,5 milhões num único projeto; o comércio atacadista de defensivos, R$ 26 milhões em seis projetos. A empresa mediana declarou R$ 2 milhões, e 49 das 129 ficaram abaixo de R$ 1 milhão.</p>
<p>No país, o ano-base 2024 fechou com 4.252 empresas, R$ 51,6 bilhões em P&amp;D e R$ 12 bilhões de renúncia estimada — os números da <a href="./cat-fiscais.html">ficha</a>.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>O que este caso ensina
</div>
</div>
<div class="callout-body-container callout-body">
<p>O retrato é o da atividade de <a href="./atividade-elegibilidade.html">elegibilidade</a>: quem usa a Lei do Bem no Centro-Oeste é a indústria, o banco, a grande produtora de soja e o frigorífico — empresas no lucro real, com lucro fiscal e contabilidade por projeto. As 129 do Centro-Oeste eram 4,3% das 3.012 empresas do país em 2021, e nenhuma delas está no Simples, por definição. Quem apura pelo presumido não aparece na base porque não pode aparecer. Usado na <a href="./s2-03-incentivos-fiscais.html">Aula 7</a>.</p>
</div>
</div>
<p>Fontes: <a href="https://dados.gov.br/dados/conjuntos-dados/beneficiarios-dos-inventivos-fiscais-da-lei-do-bem">MCTI, dados abertos — Beneficiários dos incentivos fiscais da Lei do Bem, 2015–2021 (agregação própria)</a> · <a href="https://antigo.mctic.gov.br/mctic/export/sites/institucional/tecnologia/Lei_do_bem/arquivos/RelatorioAnual/Relatorio-Anual-Lei-11196-05-Ano-Base-2015.pdf">MCTI, Relatório Anual ano-base 2015</a> · números de 2024 na <a href="./cat-fiscais.html">ficha de incentivos fiscais</a></p>
</section>
<section id="antes-de-sair" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="antes-de-sair"><span class="header-section-number">9</span> Antes de sair</h2>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>O que você deve conseguir explicar depois desta página
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li>Por que a chance de aprovação de um edital é um número que se calcula — e onde ele entra na decisão de concorrer.</li>
<li>Como a divisão de um projeto EMBRAPII pode deixar à empresa pequena só um quinto do custo, e o que conta como contrapartida.</li>
<li>O que a carência faz por um projeto financiado com dívida, e por que a notícia de crédito nunca diz o valor.</li>
<li>O que um investidor de Série A comprou na Produzindo Certo — e por que isso não descreve o seu projeto.</li>
<li>Quem aparece na base da Lei do Bem do Centro-Oeste, e quem não pode aparecer.</li>
</ol>
</div>
</div>


<script type="ojs-module-contents">
eyJjb250ZW50cyI6W119
</script>
<div id="exercise-loading-indicator" class="exercise-loading-indicator d-none d-flex align-items-center gap-2">
<div id="exercise-loading-status" class="d-flex gap-2">

</div>
<div class="spinner-grow spinner-grow-sm">

</div>
</div>
<script type="vfs-file">
WyJkYWRvcy8vQ09NTy1GT1JBTS1HRVJBRE9TLmh0bWwiLCJkYWRvcy8vZm9tZW50b19zaW0uY3N2IiwiZGFkb3MvL0NPTU8tRk9SQU0tR0VSQURPUy5tZCIsImRhZG9zLy9wcm9qZXRvX2lub3ZhY2FvLmNzdiIsImxvZ28tdW5lbWF0LnBuZyIsIm1vZGVsby1ub3RhLXRlY25pY2EuZG9jeCJd
</script>
</section>

</main> <!-- /main -->
<script type="ojs-module-contents">
eyJjb250ZW50cyI6W119
</script>
<script type="module">
if (window.location.protocol === "file:") { alert("The OJS runtime does not work with file:// URLs. Please use a web server to view this document."); }
window._ojs.paths.runtimeToDoc = "../..";
window._ojs.paths.runtimeToRoot = "../..";
window._ojs.paths.docToRoot = "";
window._ojs.selfContained = false;
window._ojs.runtime.interpretFromScriptTags();
</script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiada");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiada");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/DanielLindomar\.github\.io\/inovacao\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>Políticas e incentivos para a inovação e avaliação de impacto · Prof.&nbsp;Dr.&nbsp;Lindomar Pegorini Daniel · UNEMAT — Campus de Sinop</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>